import { afterEach, describe, expect, test } from 'vitest'
import { Sandbox } from '../../../test/support/sandbox.ts'

/**
 * TypeScript project configurations. Vite 8 discovers them in native code (rolldown's
 * TsconfigCache and oxc's resolver), which fs hooks cannot see, so Veyrum records every one in the
 * repository; a change affects only the test files whose modules it can govern.
 */

let sandbox: Sandbox | undefined
afterEach(() => sandbox?.dispose())

const valueTest = (from: string, expected: number): string =>
  `import { expect, test } from 'vitest'\nimport { value } from '${from}'\ntest('value', () => expect(value).toBe(${expected}))\n`

/**
 * A monorepo shaped like tRPC's: test files under packages/, and a Nuxt example whose `.nuxt`
 * directory holds tsconfig files that every install regenerates. No test module lives under
 * examples/.
 */
function monorepo(name: string, config = 'test: {}', prelude = ''): Sandbox {
  sandbox = new Sandbox(name)
    .write(
      'vitest.config.ts',
      `${prelude}import { defineConfig } from 'vitest/config'\nexport default defineConfig({ ${config} })\n`,
    )
    .write('tsconfig.json', '{ "compilerOptions": { "target": "es2022", "strict": true } }\n')
    .write('packages/server/tsconfig.json', '{ "extends": "../../tsconfig.json" }\n')
    .write('packages/server/src/value.ts', 'export const value = 1\n')
    .write('packages/server/test/value.test.ts', valueTest('../src/value', 1))
    .write('packages/client/tsconfig.json', '{ "extends": "../../tsconfig.json" }\n')
    .write('packages/client/src/value.ts', 'export const value = 2\n')
    .write('packages/client/test/value.test.ts', valueTest('../src/value', 2))
    .write('examples/nuxt/tsconfig.json', '{ "extends": "./.nuxt/tsconfig.json" }\n')
    .write('examples/nuxt/server/tsconfig.json', '{ "extends": "../.nuxt/tsconfig.server.json" }\n')
    .write('examples/nuxt/.nuxt/tsconfig.json', nuxtConfig('app', 1))
    .write('examples/nuxt/.nuxt/tsconfig.server.json', nuxtConfig('server', 1))
    .write('examples/nuxt/app.vue', '<template><div /></template>\n')
  return sandbox
}

/** Nuxt's generated configs differ between installs (here: a generation counter in a comment). */
function nuxtConfig(kind: string, generation: number): string {
  return `// Generated by nuxi (${kind}, generation ${generation})\n{\n  "compilerOptions": {\n    "paths": { "#app": ["../node_modules/nuxt/dist/app"], },\n  },\n  "include": ["../**/*", "./nuxt.d.ts"],\n}\n`
}

const BOTH = ['packages/client/test/value.test.ts', 'packages/server/test/value.test.ts'] as const

describe('tsconfig scope', () => {
  test('a regenerated tsconfig in an unrelated directory reruns nothing outside it', () => {
    const sb = monorepo('tsconfig-generated')
    sb.capture()
    sb.write('examples/nuxt/.nuxt/tsconfig.json', nuxtConfig('app', 2))
    sb.write('examples/nuxt/.nuxt/tsconfig.server.json', nuxtConfig('server', 2))
    const plan = sb.plan()
    for (const file of BOTH) {
      expect(plan[file]?.details).toEqual([])
      expect(plan[file]?.action).toBe('skip')
    }
  })

  test('a changed tsconfig that governs a module reruns the files that loaded it', () => {
    const sb = monorepo('tsconfig-governs')
    sb.capture()
    sb.edit(
      'packages/server/tsconfig.json',
      '"extends"',
      '"compilerOptions": { "useDefineForClassFields": false },\n  "extends"',
    )
    const plan = sb.plan()
    expect(plan['packages/server/test/value.test.ts']?.action).toBe('run')
    expect(plan['packages/server/test/value.test.ts']?.details).toEqual([
      'runner input packages/server/tsconfig.json changed',
    ])
    expect(plan['packages/client/test/value.test.ts']?.action).toBe('skip')
  })

  test('a path mapping belongs to the importer: its config, not the target directory, decides', () => {
    // The server test imports shared code through a mapping in its own config; the client test
    // imports the same file by a relative path, which no mapping can change.
    sandbox = monorepo('tsconfig-paths', 'resolve: { tsconfigPaths: true }, test: {}')
      .write('shared/one.ts', 'export const value = 1\n')
      .write('shared/two.ts', 'export const value = 2\n')
      .write(
        'packages/server/tsconfig.json',
        '{\n  "extends": "../../tsconfig.json",\n  "compilerOptions": { "paths": { "@shared/value": ["../../shared/one.ts"] } }\n}\n',
      )
      .write('packages/server/test/value.test.ts', valueTest('@shared/value', 1))
      .write('packages/client/test/value.test.ts', valueTest('../../../shared/one', 1))
    sandbox.capture()
    sandbox.edit('packages/server/tsconfig.json', 'shared/one.ts', 'shared/two.ts')
    expect(sandbox.actions()).toEqual({
      'packages/client/test/value.test.ts': 'skip',
      'packages/server/test/value.test.ts': 'run',
    })
    // What the mapping now resolves to is what the rerun sees.
    expect(sandbox.cli(['run']).code).toBe(1)
  })

  test('a changed base config reruns the files under every config that extends it', () => {
    sandbox = monorepo('tsconfig-base')
      .write(
        'configs/tsconfig.base.json',
        '{ "extends": "./strict.json", "compilerOptions": { "target": "es2022" } }\n',
      )
      .write('configs/strict.json', '{ "compilerOptions": { "strict": true } }\n')
      .write('packages/server/tsconfig.json', '{ "extends": "../../configs/tsconfig.base.json" }\n')
    sandbox.capture()
    sandbox.edit('configs/tsconfig.base.json', 'es2022', 'es2020')
    expect(sandbox.actions()).toEqual({
      'packages/client/test/value.test.ts': 'skip',
      'packages/server/test/value.test.ts': 'run',
    })
    sandbox.capture()
    // A base that is not named like a tsconfig is found through the configs that extend it.
    sandbox.edit('configs/strict.json', 'true', 'false')
    expect(sandbox.actions()).toEqual({
      'packages/client/test/value.test.ts': 'skip',
      'packages/server/test/value.test.ts': 'run',
    })
  })

  test('an unparsable tsconfig reruns everything', () => {
    const sb = monorepo('tsconfig-unparsable')
    sb.capture()
    sb.write('examples/nuxt/.nuxt/tsconfig.json', '{ "compilerOptions": ')
    for (const file of BOTH) {
      const decision = sb.plan()[file]
      expect(decision?.action).toBe('run')
      expect(decision?.reason).toBe('shared-inputs-changed')
    }
  })

  test('a tsconfig the runner reads in JavaScript reruns everything', () => {
    const sb = monorepo(
      'tsconfig-read',
      "test: { env: { NUXT: String(fs.readFileSync('examples/nuxt/.nuxt/tsconfig.json', 'utf8').length) } }",
      "import fs from 'node:fs'\n",
    )
    sb.capture()
    sb.write('examples/nuxt/.nuxt/tsconfig.json', nuxtConfig('app', 2))
    expect(sb.actions()).toEqual({ [BOTH[0]]: 'run', [BOTH[1]]: 'run' })
  })

  test('a tsconfig the Vite configuration names governs everything', () => {
    const sb = monorepo('tsconfig-named', "tsconfig: 'examples/nuxt/tsconfig.json', test: {}")
    sb.capture()
    sb.write('examples/nuxt/.nuxt/tsconfig.json', nuxtConfig('app', 2))
    expect(sb.actions()).toEqual({ [BOTH[0]]: 'run', [BOTH[1]]: 'run' })
  })

  test('a tsconfig that governs a global setup file reruns everything', () => {
    sandbox = monorepo('tsconfig-global-setup', "test: { globalSetup: ['examples/nuxt/setup.ts'] }").write(
      'examples/nuxt/setup.ts',
      'export default function setup(): void {}\n',
    )
    sandbox.capture()
    sandbox.write('examples/nuxt/.nuxt/tsconfig.json', nuxtConfig('app', 2))
    expect(sandbox.actions()).toEqual({ [BOTH[0]]: 'run', [BOTH[1]]: 'run' })
  })
})
